spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: aaaaaa
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.example.quartz.domain
  mapper-locations: classpath:mappers/**/*.xml